export const GET_MARKETS = 'GET_MARKETS';
export const GET_MARKETS_STARTED = 'GET_MARKETS_STARTED';
export const GET_MARKETS_SUCCEEDED = 'GET_MARKETS_SUCCEEDED';
export const GET_MARKETS_FAILED = 'GET_MARKETS_FAILED';

export const GET_CURRENCIES = 'GET_CURRENCIES';
export const GET_CURRENCIES_STARTED = 'GET_CURRENCIES_STARTED';
export const GET_CURRENCIES_SUCCEEDED = 'GET_CURRENCIES_SUCCEEDED';
export const GET_CURRENCIES_FAILED = 'GET_CURRENCIES_FAILED';

export const GET_TICKER = 'GET_TICKER';
export const GET_TICKER_STARTED = 'GET_TICKER_STARTED';
export const GET_TICKER_SUCCEEDED = 'GET_TICKER_SUCCEEDED';
export const GET_TICKER_FAILED = 'GET_TICKER_FAILED';

export const GET_MARKET_SUMMARIES = 'GET_MARKET_SUMMARIES';
export const GET_MARKET_SUMMARIES_STARTED = 'GET_MARKET_SUMMARIES_STARTED';
export const GET_MARKET_SUMMARIES_SUCCEEDED = 'GET_MARKET_SUMMARIES_SUCCEEDED';
export const GET_MARKET_SUMMARIES_FAILED = 'GET_MARKET_SUMMARIES_FAILED';

export const GET_MARKET_SUMMARY = 'GET_MARKET_SUMMARY';
export const GET_MARKET_SUMMARY_STARTED = 'GET_MARKET_SUMMARY_STARTED';
export const GET_MARKET_SUMMARY_SUCCEEDED = 'GET_MARKET_SUMMARY_SUCCEEDED';
export const GET_MARKET_SUMMARY_FAILED = 'GET_MARKET_SUMMARY_FAILED';

export const GET_ORDER_BOOK = 'GET_ORDER_BOOK';
export const GET_ORDER_BOOK_STARTED = 'GET_ORDER_BOOK_STARTED';
export const GET_ORDER_BOOK_SUCCEEDED = 'GET_ORDER_BOOK_SUCCEEDED';
export const GET_ORDER_BOOK_FAILED = 'GET_ORDER_BOOK_FAILED';

export const GET_MARKET_HISTORY = 'GET_MARKET_HISTORY';
export const GET_MARKET_HISTORY_STARTED = 'GET_MARKET_HISTORY_STARTED';
export const GET_MARKET_HISTORY_SUCCEEDED = 'GET_MARKET_HISTORY_SUCCEEDED';
export const GET_MARKET_HISTORY_FAILED = 'GET_MARKET_HISTORY_FAILED';

export const BUY_WITH_LIMIT = 'BUY_WITH_LIMIT';
export const BUY_WITH_LIMIT_STARTED = 'BUY_WITH_LIMIT_STARTED';
export const BUY_WITH_LIMIT_SUCCEEDED = 'BUY_WITH_LIMIT_SUCCEEDED';
export const BUY_WITH_LIMIT_FAILED = 'BUY_WITH_LIMIT_FAILED';

export const SELL_WITH_LIMIT = 'SELL_WITH_LIMIT';
export const SELL_WITH_LIMIT_STARTED = 'SELL_WITH_LIMIT_STARTED';
export const SELL_WITH_LIMIT_SUCCEEDED = 'SELL_WITH_LIMIT_SUCCEEDED';
export const SELL_WITH_LIMIT_FAILED = 'SELL_WITH_LIMIT_FAILED';

export const CANCEL_ORDER = 'CANCEL_ORDER';
export const CANCEL_ORDER_STARTED = 'CANCEL_ORDER_STARTED';
export const CANCEL_ORDER_SUCCEEDED = 'CANCEL_ORDER_SUCCEEDED';
export const CANCEL_ORDER_FAILED = 'CANCEL_ORDER_FAILED';

export const GET_OPEN_ORDERS = 'GET_OPEN_ORDERS';
export const GET_OPEN_ORDERS_STARTED = 'GET_OPEN_ORDERS_STARTED';
export const GET_OPEN_ORDERS_SUCCEEDED = 'GET_OPEN_ORDERS_SUCCEEDED';
export const GET_OPEN_ORDERS_FAILED = 'GET_OPEN_ORDERS_FAILED';

export const GET_BALANCES = 'GET_BALANCES';
export const GET_BALANCES_STARTED = 'GET_BALANCES_STARTED';
export const GET_BALANCES_SUCCEEDED = 'GET_BALANCES_SUCCEEDED';
export const GET_BALANCES_FAILED = 'GET_BALANCES_FAILED';

export const GET_BALANCE = 'GET_BALANCE';
export const GET_BALANCE_STARTED = 'GET_BALANCE_STARTED';
export const GET_BALANCE_SUCCEEDED = 'GET_BALANCE_SUCCEEDED';
export const GET_BALANCE_FAILED = 'GET_BALANCE_FAILED';

export const GET_DEPOSIT_ADDRESS = 'GET_DEPOSIT_ADDRESS';
export const GET_DEPOSIT_ADDRESS_STARTED = 'GET_DEPOSIT_ADDRESS_STARTED';
export const GET_DEPOSIT_ADDRESS_SUCCEEDED = 'GET_DEPOSIT_ADDRESS_SUCCEEDED';
export const GET_DEPOSIT_ADDRESS_FAILED = 'GET_DEPOSIT_ADDRESS_FAILED';

export const WITHDRAW = 'WITHDRAW';
export const WITHDRAW_STARTED = 'WITHDRAW_STARTED';
export const WITHDRAW_SUCCEEDED = 'WITHDRAW_SUCCEEDED';
export const WITHDRAW_FAILED = 'WITHDRAW_FAILED';

export const GET_ORDER = 'GET_ORDER';
export const GET_ORDER_STARTED = 'GET_ORDER_STARTED';
export const GET_ORDER_SUCCEEDED = 'GET_ORDER_SUCCEEDED';
export const GET_ORDER_FAILED = 'GET_ORDER_FAILED';
