export const GET_MARKETS = 'GET_MARKETS';
export const GET_MARKETS_STARTED = 'GET_MARKETS_STARTED';
export const GET_MARKETS_SUCCEEDED = 'GET_MARKETS_SUCCEEDED';
export const GET_MARKETS_FAILED = 'GET_MARKETS_FAILED';

export const GET_CURRENCIES = 'GET_CURRENCIES';
export const GET_CURRENCIES_STARTED = 'GET_CURRENCIES_STARTED';
export const GET_CURRENCIES_SUCCEEDED = 'GET_CURRENCIES_SUCCEEDED';
export const GET_CURRENCIES_FAILED = 'GET_CURRENCIES_FAILED';

export const GET_TICKER = 'GET_TICKER';
export const GET_TICKER_STARTED = 'GET_TICKER_STARTED';
export const GET_TICKER_SUCCEEDED = 'GET_TICKER_SUCCEEDED';
export const GET_TICKER_FAILED = 'GET_TICKER_FAILED';

export const GET_MARKET_SUMMARIES = 'GET_MARKET_SUMMARIES';
export const GET_MARKET_SUMMARIES_STARTED = 'GET_MARKET_SUMMARIES_STARTED';
export const GET_MARKET_SUMMARIES_SUCCEEDED = 'GET_MARKET_SUMMARIES_SUCCEEDED';
export const GET_MARKET_SUMMARIES_FAILED = 'GET_MARKET_SUMMARIES_FAILED';
