export const GET_MARKET_SUMMARIES = 'GET_MARKET_SUMMARIES';
export const GET_MARKET_SUMMARIES_STARTED = 'GET_MARKET_SUMMARIES_STARTED';
export const GET_MARKET_SUMMARIES_SUCCEEDED = 'GET_MARKET_SUMMARIES_SUCCEEDED';
export const GET_MARKET_SUMMARIES_FAILED = 'GET_MARKET_SUMMARIES_FAILED';
export const GET_MARKET_SUMMARIES_ENDED = 'GET_MARKET_SUMMARIES_ENDED';
